[versions]
kotlin = "2.2.0"
framework = "2025.05.23-Beta-12"
neoforged = "2.0.116"
slf4j = "2.0.16"
logback = "1.5.12"
awaitility = "4.2.2"
junit = "5.10.5"
shadow = "9.2.2"

[libraries]
framework-core = { group = "live.lingting.framework", name = "lingting-core", version.ref = "framework" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

[bundles]
dependencies = []
annotation = []
implementation = ["kotlin-stdlib"]
compile = []
test = ["awaitility", "junit", "logback"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
neoforged-modedev = { id = "net.neoforged.moddev", version.ref = "neoforged" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
